### ISSUE TITLE
License text in README.md is wrong

### ISSUE THREAD

**Issue by briansmith** [heartsucker/derp#1]
README.md says "This work is dual licensed under the MIT and Apache-2.0 licenses. see LICENSE-MIT and LICENSE-APACHE for details," but at least a significant chunk of this is licensed under the ISC license.

**Comment by heartsucker** [comment]
Ah, sorry about that. I thought I recognized that as MIT. What would say the appropriate way to resolve this is? Dual ISC/Apache?

**Comment by briansmith** [comment]
If you want to discuss changing the license of that code then email me: brian@briansmith.org.
